// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS0_A54lN9qvNsDPISi0YA-tA3QYt-tKA',
    appId: '1:335988170042:android:a56c408165c281c458c403',
    messagingSenderId: '335988170042',
    projectId: 'backup-2b746',
    storageBucket: 'backup-2b746.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo0IDds1gD6HzdvYKkerJOwU74JRAoc0k',
    appId: '1:335988170042:ios:7327b2af50424bc358c403',
    messagingSenderId: '335988170042',
    projectId: 'backup-2b746',
    storageBucket: 'backup-2b746.firebasestorage.app',
    androidClientId: '335988170042-j4cmkpmscu9emnjrdgakfkqv4q2rfbdo.apps.googleusercontent.com',
    iosClientId: '335988170042-mib1pef32u81f1qm7dakai0a7ftmv92u.apps.googleusercontent.com',
    iosBundleId: 'com.app.chys',
  );

}