-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgmyu5QiIYJw6ZWqWn
u+1iI9uckeoABf1orlb2GW9wMOqgCgYIKoZIzj0DAQehRANCAASfxS6ZR61IRLJ2
2+IwL2QovjZ+V3Np0lwtcjZvOLr1tyjVOi8I49udqqGndJuiy6rZNUHYzkMbeiEN
ouivmxmv
-----END PRIVATE KEY-----